sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - g++
    - swig
    - build-essential
cache:
  directories:

before_install:
  # ============== Handle Python third-party packages ==============
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy h5py pandas
  - source activate test-environment

install: true

script:
  - cd tests
  - ./travis.sh
  - cd ..